# Site settings
title: @OtherAssorted
tag_text: Other Assorted
description: Unassuming enough that my username isn't considered plagiarism.
url: "http://127.0.0.1:4000"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
